version: 1.0.{build}
image: Visual Studio 2019
environment:
  URL:
    secure: cJUFr2NsBjDh6gZxnshL2HMwKuFcjj4JxyfYgTAwY4EaegRkArES3eXzLKOPnUNL3WZddVReEfJCXN81s0sLBA==
build_script:
- cmd: |
    appveyor DownloadFile https://github.com/maxim-zhao/sms-build-tools/releases/download/1.0.102/tools.7z
    7z x tools.7z -otools
    path %cd%\tools;%path%
    appveyor DownloadFile -Url %URL% -FileName ps.zip
    7z x ps.zip -opsrp
    cd psrp
    py -m pip install PyYAML
    make LANGUAGE=en
    make clean
    make LANGUAGE=fr
    make clean
    make LANGUAGE=pt-br
    make clean
    make LANGUAGE=ca
	make clean
	make LANGUAGE=es
    7z a ..\psrp.zip *.?ps ..\readme.md
artifacts:
- path: psrp.zip
  name: psrp
